version: '3'
volumes:
    mongo-data:
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  app:
    build:
      context: ./app
    volumes:
      - type: bind
        source: ./app
        target: /app/src
    ports:
      - 8888:8000
    environment:
      - PYTHONPATH=/app/src/
    restart: always
    stdin_open: true
    tty: true
  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    tty: true